---
- hosts: all
  become: yes
  tasks:
- name: install git,tree and wget
  apt:
      name: "{{item}}"
      state: present
  with_items:
       - git
       - tree 
       - wget 

  when: ansible_os_family == "Debian"


